# Allow direct execution
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import toml

VERSION_TEMPLATE = '''\
# Autogenerated by devscripts/update-version.py

__version__ = {version!r}
'''

def read_pyproject_version(pyproject_path="pyproject.toml") -> str:
    '''
    Read version information from pyproject.toml.
    
    Parameters
    ----------
    pyproject_path : str
        Path to pyproject.toml
    
    Returns
    -------
    str
        Version information
    '''
    with open(pyproject_path, "r") as f:
        pyproject = toml.load(f)
    return pyproject["tool"]["poetry"]["version"]

def write_version_file(version, output_path="radiko_recorder/version.py"):
    '''
    Write version information to version.py.
    
    Parameters
    ----------
    version : str
        Version information
    output_path : str
        Path to version.py
    '''
    with open(output_path, "w") as f:
        f.write(VERSION_TEMPLATE.format(version=version))
    print(f"version.py has been generated with version: {version}")

if __name__ == "__main__":
    version = read_pyproject_version()
    write_version_file(version)